[package]
name = "AniON-Bot"
version = "0.1.0"
authors = ["Gaeulbyul <aeiou256@gmail.com>"]

[dependencies]
serde = "0.8.3"
serde_json = "0.8.3"
hyper = "0.9.12"
telegram-bot = "0.5.0"
regex = "0.1"
iron = "0.4.0"
router = "0.2"
rustc-serialize = "0.3"
